-- Северная звезда — SECURITY HARDENING v4
-- ЕДИНАЯ идемпотентная миграция для текущей production-базы.
-- Включает: полный прайс, 30-минутный травматолог, admin-comfort schema и защиту БД.
-- Можно выполнить повторно: данные записей не удаляются.

create extension if not exists pgcrypto;

-- Совместимость со старыми production-сборками.
alter table public.bookings add column if not exists archived_at timestamptz;
alter table public.bookings add column if not exists client_notice_reason text;
alter table public.clinic_services add column if not exists duration_minutes integer not null default 20;

create table if not exists public.clinic_settings(
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.schedule_blocks(
  id bigint generated by default as identity primary key,
  block_date date not null,
  start_time time,
  end_time time,
  reason text not null default 'Недоступно',
  created_at timestamptz not null default now(),
  constraint schedule_blocks_time_check check(
    (start_time is null and end_time is null) or
    (start_time is not null and end_time is not null and end_time > start_time)
  )
);
create index if not exists schedule_blocks_date_idx on public.schedule_blocks(block_date,start_time);

create table if not exists public.booking_audit(
  id bigint generated by default as identity primary key,
  booking_id bigint not null references public.bookings(id) on delete cascade,
  actor text not null check(actor in ('client','admin','system')),
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists booking_audit_booking_idx on public.booking_audit(booking_id,created_at desc);

-- В старой БД whitelist clinic_services не знал о новых направлениях.
alter table public.clinic_services drop constraint if exists clinic_services_key_check;
alter table public.clinic_services add constraint clinic_services_key_check
check(service_key in ('exam','ultrasound','xray','vaccination','tests','surgery','dentistry','farm','other','inpatient'));

-- Северная звезда — прайс, новые направления записи и 30-минутный травматолог.
-- Идемпотентная миграция: можно запускать повторно.

alter table public.bookings add column if not exists client_notice_reason text;

alter table public.bookings drop constraint if exists bookings_service_check;

alter table public.bookings add constraint bookings_service_check check(service in ('exam','ultrasound','xray','vaccination','tests','surgery','dentistry','farm','other','inpatient'));

delete from public.clinic_services where service_key='inpatient';

insert into public.clinic_services(service_key,name,icon,price_label,description,prep,duration_minutes,sort_order,enabled) values

('exam','Осмотр и консультация','stethoscope','850 ₽','Приём врача, консультация и первичная оценка состояния.','Возьмите ветпаспорт и имеющиеся результаты обследований.',20,10,true),
('ultrasound','УЗИ','ultrasound','от 850 ₽','Ультразвуковая диагностика по выбранной области.','Подготовка зависит от исследования — клиника уточнит её при необходимости.',20,20,true),
('xray','Рентген','xray','от 1 000 ₽','Рентгенологическая диагностика нужной области.','Если есть прежние снимки или заключения, возьмите их с собой.',20,30,true),
('vaccination','Вакцинация','syringe','от 500 ₽','Вакцинация кошек и собак по актуальному прайсу.','Возьмите ветеринарный паспорт.',20,40,true),
('tests','Анализы','flask','по прайсу','Лабораторные исследования и забор материала.','Подготовка зависит от анализа.',20,50,true),
('surgery','Хирургия','scalpel','по прайсу','Хирургические вмешательства и предоперационная консультация.','Условия подготовки согласуются с клиникой.',20,60,true),
('dentistry','Стоматология','tooth','по прайсу','Удаление зубов и ультразвуковая санация ротовой полости.','Необходимость седации и подготовка уточняются заранее.',20,70,true),
('farm','Сельскохозяйственные животные','farm','по прайсу','Осмотр, диагностика и процедуры для сельскохозяйственных животных.','Уточните вид животного и нужную помощь в заявке.',20,80,true),
('other','Другое','paw','уточним','Если нужная услуга не относится к направлениям выше, опишите запрос.','Администратор уточнит детали после получения заявки.',20,90,true)
on conflict(service_key) do update set name=excluded.name,icon=excluded.icon,price_label=excluded.price_label,description=excluded.description,prep=excluded.prep,duration_minutes=excluded.duration_minutes,sort_order=excluded.sort_order,enabled=excluded.enabled,updated_at=now();

delete from public.clinic_settings where key='inpatient_capacity';

create table if not exists public.clinic_price_items(
  item_key text primary key,
  category text not null,
  name text not null,
  price_label text not null,
  booking_service text not null default 'exam',
  category_order integer not null default 100,
  sort_order integer not null default 100,
  enabled boolean not null default true,
  updated_at timestamptz not null default now()
);

alter table public.clinic_price_items enable row level security;

do $$ declare r record; begin for r in select policyname from pg_policies where schemaname='public' and tablename='clinic_price_items' loop execute format('drop policy if exists %I on public.clinic_price_items',r.policyname); end loop; end $$;

revoke all on public.clinic_price_items from anon,authenticated;

insert into public.clinic_price_items(item_key,category,name,price_label,booking_service,category_order,sort_order,enabled) values

('general-001','Общие услуги','Консультация без животного (кошки, собаки)','500 ₽','exam',10,10,true),
('general-002','Общие услуги','Первичный приём животного','850 ₽','exam',10,20,true),
('general-003','Общие услуги','Чипирование (с внесением в единую базу)','1 500 ₽','exam',10,30,true),
('general-004','Общие услуги','Первичный приём специалиста узкого профиля','1 600 ₽','exam',10,40,true),
('general-005','Общие услуги','Повторный приём специалиста узкого профиля','850 ₽','exam',10,50,true),
('general-006','Общие услуги','Оформление вет. паспорта без учёта его стоимости','500 ₽','exam',10,60,true),
('general-007','Общие услуги','Забор крови из вены','кошки — 400 ₽; собаки — 450 ₽; хорьки — 500 ₽; КРС — 500 ₽','tests',10,70,true),
('general-008','Общие услуги','Забор материала на бак. посев','150 ₽','tests',10,80,true),
('general-009','Общие услуги','Экспресс-анализ мочи с консультацией','1 100 ₽','tests',10,90,true),
('general-010','Общие услуги','Люм. диагностика','300 ₽','tests',10,100,true),
('general-011','Общие услуги','Микроскопия соскобов на эктопаразитов','600 ₽','tests',10,110,true),
('general-012','Общие услуги','Биохимический анализ крови','от 1 450 ₽','tests',10,120,true),
('general-013','Общие услуги','Биохимический анализ крови (экспресс)','от 1 450 ₽','tests',10,130,true),
('general-014','Общие услуги','Клинический анализ крови','от 1 100 ₽','tests',10,140,true),
('general-015','Общие услуги','П/к и в/м инъекции','120 ₽','exam',10,150,true),
('general-016','Общие услуги','Катетеризация вены','кошки — 450 ₽; собаки — 550 ₽','exam',10,160,true),
('general-017','Общие услуги','В/в введение без стоимости препарата и без присутствия владельца','630 ₽','exam',10,170,true),
('general-018','Общие услуги','В/в введение без стоимости препарата','350 ₽','exam',10,180,true),
('general-019','Общие услуги','Катетеризация мочевого пузыря','от 1 000 ₽','exam',10,190,true),
('general-020','Общие услуги','Лечебная блокада','от 350 ₽','exam',10,200,true),
('general-021','Общие услуги','Перевязка животного','от 370 ₽','exam',10,210,true),
('general-022','Общие услуги','Обработка раны с промыванием','от 350 ₽','exam',10,220,true),
('general-023','Общие услуги','Чистка ушей','кошки — 450 ₽; собаки — 500 ₽','exam',10,230,true),
('general-024','Общие услуги','Обработка глаз, нос., рот. полостей','200 ₽','exam',10,240,true),
('general-025','Общие услуги','Дача лек. средств, постановка свечей','кошки — 300 ₽; собаки — 400 ₽','exam',10,250,true),
('general-026','Общие услуги','Стрижка когтей','кошки — 400 ₽; собаки — от 450 ₽','exam',10,260,true),
('general-027','Общие услуги','Удаление параанальных желез','кошки — 450 ₽; собаки — 550 ₽','exam',10,270,true),
('general-028','Общие услуги','Снятие швов','400 ₽','exam',10,280,true),
('general-029','Общие услуги','Удаление клеща','200 ₽','exam',10,290,true),
('general-030','Общие услуги','Эвакуация асептической жидкости','от 1 000 ₽','exam',10,300,true),
('general-031','Общие услуги','Эвакуация каловых масс','от 2 000 ₽','exam',10,310,true),
('general-032','Общие услуги','Постановка микроклизм без стоимости препарата','200 ₽','exam',10,320,true),
('general-033','Общие услуги','Обработка швов, ссадин, парезов с применением аэрозолей','300 ₽','exam',10,330,true),
('general-034','Общие услуги','Местная анестезия','250 ₽','exam',10,340,true),
('general-035','Общие услуги','УЗИ (мелкие животные)','по прайсу','ultrasound',10,350,true),
('general-036','Общие услуги','Фиксация животного (фикс. сумка)','кошки — 400 ₽; мелкие собаки — 450 ₽','exam',10,360,true),
('general-037','Общие услуги','Фиксация животного (выше 25 кг)','700 ₽','exam',10,370,true),
('general-038','Общие услуги','Фиксация намордником','кошки — 150 ₽; собаки — 200 ₽','exam',10,380,true),
('general-039','Общие услуги','Стрижка колтунов','700 ₽','exam',10,390,true),
('general-040','Общие услуги','Вызов врача на дом + осмотр (в черте города)','1 500 ₽','other',10,400,true),
('general-041','Общие услуги','Вызов врача на дом + осмотр + отдельная оплата за 1 км (район)','60 ₽ за 1 км','other',10,410,true),
('general-042','Общие услуги','Транспортировка животного','кошка — 500 ₽; собака — 1 000 ₽','other',10,420,true),
('general-043','Общие услуги','Эвтаназия','кошки, собаки до 10 кг — 3 000 ₽; собаки более 10 кг — 250 ₽ за 1 кг','other',10,430,true),
('general-044','Общие услуги','Оксигенотерапия','кошки — 350 ₽; собаки — 500 ₽','exam',10,440,true),
('general-045','Общие услуги','Вскрытие трупов для диагностики без заключения','кошки — от 3 000 ₽; собаки — от 5 000 ₽; птицы — 1 500 ₽','other',10,450,true),
('general-046','Общие услуги','Вскрытие трупов для диагностики с заключением','10 000 ₽','other',10,460,true),
('general-047','Общие услуги','Выписка из амбулаторной карты','500 ₽','exam',10,470,true),
('general-048','Общие услуги','Выдача справки о наличии вакцины','350 ₽','vaccination',10,480,true),
('general-049','Общие услуги','Зоотакси (в черте города)','500 ₽','other',10,490,true),
('general-050','Общие услуги','Утилизация трупа','500 ₽ за 1 кг','other',10,500,true),
('general-051','Общие услуги','Введение животного в наркоз с использованием вет. оборудования (без стоимости наркоза)','от 1 000 ₽','surgery',10,510,true),
('general-052','Общие услуги','Стоимость любых услуг в нерабочее время','×1,4 к базовой стоимости','other',10,520,true),
('vaccination-001','Вакцинация','Вангард (собака)','2 500 ₽','vaccination',20,10,true),
('vaccination-002','Вакцинация','Биокан DHPPI+L (собака)','2 000 ₽','vaccination',20,20,true),
('vaccination-003','Вакцинация','Биокан DHPPI+LR (собака)','2 500 ₽','vaccination',20,30,true),
('vaccination-004','Вакцинация','Биофел 1 (кошка)','2 000 ₽','vaccination',20,40,true),
('vaccination-005','Вакцинация','Биофел 2 (кошка)','2 500 ₽','vaccination',20,50,true),
('vaccination-006','Вакцинация','Астерион первичный (собака)','2 000 ₽','vaccination',20,60,true),
('vaccination-007','Вакцинация','Астерион вторичный (собака)','2 200 ₽','vaccination',20,70,true),
('vaccination-008','Вакцинация','Рабифел (кошка)','500 ₽','vaccination',20,80,true),
('vaccination-009','Вакцинация','Рабикс (собака)','500 ₽','vaccination',20,90,true),
('vaccination-010','Вакцинация','Мультифел (кошка)','1 800 ₽','vaccination',20,100,true),
('vaccination-011','Вакцинация','Мультикан-6 (собака)','1 600 ₽','vaccination',20,110,true),
('vaccination-012','Вакцинация','Мультикан-8 (собака)','1 800 ₽','vaccination',20,120,true),
('vaccination-013','Вакцинация','Фелоцел (кошка)','2 300 ₽','vaccination',20,130,true),
('vaccination-014','Вакцинация','Астерион (первич.) (собака)','1 600 ₽','vaccination',20,140,true),
('vaccination-015','Вакцинация','Астерион (вторич.) (собака)','1 800 ₽','vaccination',20,150,true),
('surgery-001','Хирургические вмешательства','Кастрация кота','2 000 ₽','surgery',30,10,true),
('surgery-002','Хирургические вмешательства','Кастрация кота крипторха','2 900 ₽','surgery',30,20,true),
('surgery-003','Хирургические вмешательства','Кастрация кобеля до 10 кг','3 000 ₽','surgery',30,30,true),
('surgery-004','Хирургические вмешательства','Кастрация кобеля крипторха','4 000 ₽','surgery',30,40,true),
('surgery-005','Хирургические вмешательства','Кастрация кобеля 10–15 кг','4 200 ₽','surgery',30,50,true),
('surgery-006','Хирургические вмешательства','Кастрация кобеля 10–15 кг крипторха','5 200 ₽','surgery',30,60,true),
('surgery-007','Хирургические вмешательства','Кастрация кобеля свыше 15–20 кг','5 500 ₽','surgery',30,70,true),
('surgery-008','Хирургические вмешательства','Кастрация кобеля свыше 25 кг крипторха','6 200 ₽','surgery',30,80,true),
('surgery-009','Хирургические вмешательства','Овариоэктомия','кошки — 3 100 ₽; собаки до 10 кг — 3 800 ₽; 10–25 кг — от 4 800 ₽; свыше 25 кг — от 10 000 ₽','surgery',30,90,true),
('surgery-010','Хирургические вмешательства','Овариогистерэктомия','кошки — 5 000 ₽; собаки до 10 кг — 6 500 ₽; 10–25 кг — 7 000 ₽; свыше 25 кг — от 12 000 ₽','surgery',30,100,true),
('surgery-011','Хирургические вмешательства','Кесарево сечение','кошка — 8 500 ₽; собака до 10 кг — 12 000 ₽; 10–25 кг — 15 000 ₽; свыше 25 кг — от 20 000 ₽','surgery',30,110,true),
('surgery-012','Хирургические вмешательства','Диагностическая лапаротомия','кошка — от 3 200 ₽; собака до 10 кг — от 3 500 ₽; 10–25 кг — от 4 500 ₽; свыше 25 кг — от 8 000 ₽','surgery',30,120,true),
('surgery-013','Хирургические вмешательства','Грыжесечение','кошка — 3 000 ₽; собака до 10 кг — 4 000 ₽; 10–25 кг — от 4 500 ₽; свыше 25 кг — от 7 000 ₽','surgery',30,130,true),
('surgery-014','Хирургические вмешательства','Вскрытие абсцесса','1 000 ₽','surgery',30,140,true),
('surgery-015','Хирургические вмешательства','Вскрытие неосложнённой гематомы уха','кот — 1 200 ₽; собака — от 1 500 ₽','surgery',30,150,true),
('surgery-016','Хирургические вмешательства','Купирование хвоста','до 1 мес — 500 ₽; от месяца — от 2 000 ₽','surgery',30,160,true),
('surgery-017','Хирургические вмешательства','Ампутация хвоста','кот — 2 500 ₽; собака — от 3 000 ₽','surgery',30,170,true),
('surgery-018','Хирургические вмешательства','Купирование прибылых пальцев','до 1 мес — 400 ₽; от 1 месяца — от 1 000 ₽','surgery',30,180,true),
('surgery-019','Хирургические вмешательства','Купирование ушей','до 1 месяца — 2 000 ₽; от 1 месяца — 5 500 ₽','surgery',30,190,true),
('surgery-020','Хирургические вмешательства','Цистолитотрипсия (удаление камней) мочевого пузыря','кот — 5 500 ₽; собака — от 7 000 ₽','surgery',30,200,true),
('surgery-021','Хирургические вмешательства','Удаление новообразования: кошка и мелкая порода собак','до 5 см — 3 700 ₽; 5–10 см — 5 000 ₽; свыше 10 см — 7 000 ₽','surgery',30,210,true),
('surgery-022','Хирургические вмешательства','Удаление новообразования у собак весом более 10 кг','от 6 000 ₽','surgery',30,220,true),
('surgery-023','Хирургические вмешательства','Операция на кишечнике','кошки — от 5 000 ₽; собаки весом более 15 кг — от 8 000 ₽','surgery',30,230,true),
('surgery-024','Хирургические вмешательства','Удаление новообразования из внутренних органов','кошки — от 7 000 ₽; собаки весом более 15 кг — от 10 000 ₽','surgery',30,240,true),
('surgery-025','Хирургические вмешательства','Удаление зубов','молочные клыки — 500 ₽; резцы — 400 ₽; коренной зуб (без стоимости наркоза) — 1 000 ₽','dentistry',30,250,true),
('surgery-026','Хирургические вмешательства','Ультразвуковая санация ротовой полости без стоимости седации','кошки — 1 800 ₽; собаки — 2 000 ₽; собаки более 15 кг — от 3 000 ₽','dentistry',30,260,true),
('surgery-027','Хирургические вмешательства','Удаление аденомы третьего века','кошка — 3 500 ₽; собака весом более 15 кг — от 4 500 ₽','surgery',30,270,true),
('surgery-028','Хирургические вмешательства','Энтропион (заворот век)','кошка — от 2 000 ₽; собака от 15 кг — от 4 000 ₽','surgery',30,280,true),
('surgery-029','Хирургические вмешательства','Удаление глазного яблока','кошка — 2 500 ₽; собака свыше 15 кг — от 3 000 ₽','surgery',30,290,true),
('surgery-030','Хирургические вмешательства','Первичная хирургическая обработка','от 1 500 ₽','surgery',30,300,true),
('surgery-031','Хирургические вмешательства','Ампутация конечностей','кошки — от 5 000 ₽; собаки свыше 15 кг — от 10 000 ₽','surgery',30,310,true),
('surgery-032','Хирургические вмешательства','Пролапс влагалища (без стоимости наркоза)','кошки — от 3 700 ₽; собаки — от 4 000 ₽','surgery',30,320,true),
('surgery-033','Хирургические вмешательства','Пролапс прямой кишки (без стоимости наркоза)','кошки — от 3 500 ₽; собаки — от 5 500 ₽','surgery',30,330,true),
('surgery-034','Хирургические вмешательства','Реанимация новорождённых за 1 голову','500 ₽','surgery',30,340,true),
('surgery-035','Хирургические вмешательства','Родовспоможение','кошки — от 2 500 ₽; собаки — от 4 000 ₽; каждый последующий час — 400 ₽','surgery',30,350,true),
('surgery-036','Хирургические вмешательства','Оперативное вмешательство на диафрагме','кошка — от 8 000 ₽; собака — от 10 000 ₽','surgery',30,360,true),
('surgery-037','Хирургические вмешательства','Остеосинтез конечностей (без стоимости материалов)','от 15 000 ₽','surgery',30,370,true),
('surgery-038','Хирургические вмешательства','Наложение гипсовой эмболии','от 2 000 ₽','surgery',30,380,true),
('xray-001','Рентген','Рентгеновский снимок тазовых конечностей','1 000 ₽','xray',40,10,true),
('xray-002','Рентген','Рентген грудной клетки','1 000 ₽','xray',40,20,true),
('xray-003','Рентген','Рентген брюшной полости','1 000 ₽','xray',40,30,true),
('xray-004','Рентген','Рентген с барием','1 500 ₽','xray',40,40,true),
('xray-005','Рентген','Рентген черепа','1 000 ₽','xray',40,50,true),
('xray-006','Рентген','Рентген грудных конечностей','1 000 ₽','xray',40,60,true),
('farm-001','Сельскохозяйственные животные','Внутривенное введение','от 1 000 ₽','farm',50,10,true),
('farm-002','Сельскохозяйственные животные','П/к, в/м инъекции','150 ₽','farm',50,20,true),
('farm-003','Сельскохозяйственные животные','Отделение последа (без стоимости медикаментов)','от 4 000 ₽','farm',50,30,true),
('farm-004','Сельскохозяйственные животные','Осмотр','1 000 ₽','farm',50,40,true),
('farm-005','Сельскохозяйственные животные','Обезроживание от 1–3 дней с рождения','500 ₽','farm',50,50,true),
('farm-006','Сельскохозяйственные животные','Кастрация хряка','до 1 месяца — 600 ₽; старше 1 месяца — от 1 000 ₽; старше 8 месяцев (без стоимости медикаментов) — от 10 000 ₽','farm',50,60,true),
('farm-007','Сельскохозяйственные животные','Кастрация козла','до 1 месяца — 550 ₽; с 3 месяцев до 1 года (без стоимости медикаментов) — от 3 500 ₽','farm',50,70,true),
('farm-008','Сельскохозяйственные животные','Б/х анализ крови, 1 показатель','300 ₽','farm',50,80,true),
('farm-009','Сельскохозяйственные животные','Клинический анализ','1 200 ₽','farm',50,90,true),
('farm-010','Сельскохозяйственные животные','Обрезка копыт','КРС — 3 000 ₽ за одно копыто; козы — 1 000 ₽ за одно копыто','farm',50,100,true),
('farm-011','Сельскохозяйственные животные','УЗИ','1 000 ₽','farm',50,110,true),
('farm-012','Сельскохозяйственные животные','Надувание вымени при родовом парезе','1 000 ₽','farm',50,120,true),
('farm-013','Сельскохозяйственные животные','Исследование молока на мастит','300 ₽','farm',50,130,true),
('farm-014','Сельскохозяйственные животные','Внутриматочное, внутривыменное введение','400 ₽','farm',50,140,true),
('farm-015','Сельскохозяйственные животные','Наложение швов','от 3 000 ₽','farm',50,150,true),
('farm-016','Сельскохозяйственные животные','Родовспоможение','от 10 000 ₽','farm',50,160,true),
('farm-017','Сельскохозяйственные животные','Вправление матки','от 15 000 ₽','farm',50,170,true),
('farm-018','Сельскохозяйственные животные','Забор крови без стоимости пробирки','350 ₽','farm',50,180,true),
('farm-019','Сельскохозяйственные животные','Забор материала на посев','500 ₽','farm',50,190,true),
('farm-020','Сельскохозяйственные животные','Исследование на яйцеглист','1 200 ₽','farm',50,200,true),
('farm-021','Сельскохозяйственные животные','Внутрирубцовое введение','от 600 ₽','farm',50,210,true),
('farm-022','Сельскохозяйственные животные','Обламывание резцов свинье','от 1 000 ₽','farm',50,220,true),
('farm-023','Сельскохозяйственные животные','Чипирование','1 500 ₽','farm',50,230,true),
('ultrasound-001','УЗИ','УЗИ одного органа','850 ₽','ultrasound',60,10,true),
('ultrasound-002','УЗИ','УЗИ МПС','1 000 ₽','ultrasound',60,20,true),
('ultrasound-003','УЗИ','УЗИ ЖКТ','1 200 ₽','ultrasound',60,30,true),
('ultrasound-004','УЗИ','УЗИ брюшной полости обзорное','1 500 ₽','ultrasound',60,40,true),
('ultrasound-005','УЗИ','УЗИ половой системы','900 ₽','ultrasound',60,50,true)
on conflict(item_key) do update set category=excluded.category,name=excluded.name,price_label=excluded.price_label,booking_service=excluded.booking_service,category_order=excluded.category_order,sort_order=excluded.sort_order,enabled=excluded.enabled,updated_at=now();

delete from public.clinic_price_items where item_key like any(array['general-%','vaccination-%','surgery-%','xray-%','farm-%','ultrasound-%']) and item_key not in ('general-001','general-002','general-003','general-004','general-005','general-006','general-007','general-008','general-009','general-010','general-011','general-012','general-013','general-014','general-015','general-016','general-017','general-018','general-019','general-020','general-021','general-022','general-023','general-024','general-025','general-026','general-027','general-028','general-029','general-030','general-031','general-032','general-033','general-034','general-035','general-036','general-037','general-038','general-039','general-040','general-041','general-042','general-043','general-044','general-045','general-046','general-047','general-048','general-049','general-050','general-051','general-052','vaccination-001','vaccination-002','vaccination-003','vaccination-004','vaccination-005','vaccination-006','vaccination-007','vaccination-008','vaccination-009','vaccination-010','vaccination-011','vaccination-012','vaccination-013','vaccination-014','vaccination-015','surgery-001','surgery-002','surgery-003','surgery-004','surgery-005','surgery-006','surgery-007','surgery-008','surgery-009','surgery-010','surgery-011','surgery-012','surgery-013','surgery-014','surgery-015','surgery-016','surgery-017','surgery-018','surgery-019','surgery-020','surgery-021','surgery-022','surgery-023','surgery-024','surgery-025','surgery-026','surgery-027','surgery-028','surgery-029','surgery-030','surgery-031','surgery-032','surgery-033','surgery-034','surgery-035','surgery-036','surgery-037','surgery-038','xray-001','xray-002','xray-003','xray-004','xray-005','xray-006','farm-001','farm-002','farm-003','farm-004','farm-005','farm-006','farm-007','farm-008','farm-009','farm-010','farm-011','farm-012','farm-013','farm-014','farm-015','farm-016','farm-017','farm-018','farm-019','farm-020','farm-021','farm-022','farm-023','ultrasound-001','ultrasound-002','ultrasound-003','ultrasound-004','ultrasound-005');

-- Старые записи, существовавшие до этого обновления, не удаляются.


-- Обновляем последний рубеж против дублей: разные конкретные позиции одного направления
-- (например, два разных анализа) не считаются одной и той же заявкой.
create or replace function public.guard_public_booking_insert()
returns trigger language plpgsql set search_path=public as $$
declare v_recent integer;
begin
  if new.request_id is null then return new; end if;
  if coalesce(new.phone_norm,'')='' then raise exception 'BOOKING_RATE_LIMIT'; end if;
  if exists(
    select 1 from public.bookings b
    where b.request_id is not null
      and b.phone_norm=new.phone_norm
      and lower(trim(b.pet))=lower(trim(new.pet))
      and b.service=new.service
      and lower(trim(coalesce(b.service_details->>'interest','')))=lower(trim(coalesce(new.service_details->>'interest','')))
      and b.created_at>now()-interval '30 minutes'
      and b.status not in ('rejected','cancelled')
      and b.archived_at is null
  ) then raise exception 'DUPLICATE_BOOKING'; end if;
  select count(*) into v_recent from public.bookings b
  where b.request_id is not null
    and b.phone_norm=new.phone_norm
    and b.created_at>now()-interval '30 minutes';
  if v_recent>=3 then raise exception 'BOOKING_RATE_LIMIT'; end if;
  return new;
end $$;

drop trigger if exists trg_guard_public_booking_insert on public.bookings;
create trigger trg_guard_public_booking_insert before insert on public.bookings for each row execute function public.guard_public_booking_insert();



-- Северная звезда — удобство администрирования сайта.
-- Идемпотентная миграция. Не меняет прайс и не сбрасывает цены.

create table if not exists public.clinic_settings(
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

insert into public.clinic_settings(key,value)
values(
  'public_site',
  jsonb_build_object(
    'phone_display','+7 911 648-06-44',
    'phone_tel','+79116480644',
    'address','ул. Северная, д. 7 · Малая Вишера',
    'map_query','Малая Вишера, ул. Северная, 7',
    'hero_lead','Выберите услугу и удобное время онлайн. Если случай срочный или вы сомневаетесь, какой приём нужен, просто позвоните — подскажем, как лучше поступить.',
    'urgent_text','Если питомцу требуется срочная помощь, позвоните в клинику перед поездкой.',
    'announcement_enabled',false,
    'announcement_text','',
    'announcement_until',null
  )
)
on conflict(key) do nothing;

alter table public.clinic_settings enable row level security;
revoke all on public.clinic_settings from anon,authenticated;


-- ================================================================
-- SECURITY HARDENING: прямой доступ к БД закрыт, сайт работает через Netlify Functions.
-- ================================================================

-- Токены новых записей — 32 случайных байта (64 hex). Старые 48-символьные ссылки остаются валидны.
alter table public.bookings alter column public_token set default encode(extensions.gen_random_bytes(32),'hex');
update public.bookings set public_token=encode(extensions.gen_random_bytes(32),'hex') where public_token is null or public_token='';
alter table public.bookings alter column public_token set not null;
alter table public.bookings drop constraint if exists bookings_public_token_format_check;
alter table public.bookings add constraint bookings_public_token_format_check
check(public_token ~ '^([0-9a-fA-F]{48}|[0-9a-fA-F]{64})$') not valid;
alter table public.bookings validate constraint bookings_public_token_format_check;
create unique index if not exists bookings_public_token_unique on public.bookings(public_token);
create unique index if not exists bookings_request_id_unique on public.bookings(request_id) where request_id is not null;

-- Уникальный активный слот закрывает race condition двух одновременных клиентов.
drop index if exists public.bookings_date_time_unique;
create unique index bookings_date_time_unique on public.bookings(booking_date,booking_time)
where service <> 'inpatient' and status not in ('rejected','cancelled') and archived_at is null;

-- Ограничиваем допустимое направление каждой строки прайса.
alter table public.clinic_price_items drop constraint if exists clinic_price_items_booking_service_check;
alter table public.clinic_price_items add constraint clinic_price_items_booking_service_check
check(booking_service in ('exam','ultrasound','xray','vaccination','tests','surgery','dentistry','farm','other'));
alter table public.clinic_price_items drop constraint if exists clinic_price_items_key_format_check;
alter table public.clinic_price_items add constraint clinic_price_items_key_format_check
check(item_key ~ '^[a-z]+-[0-9]{3}$');

-- Убираем дублирующий индекс, сохраняя UNIQUE constraint endpoint.
drop index if exists public.push_subscriptions_endpoint_unique;

-- Rate-limit RPC: только service_role, фиксированный search_path, без динамического SQL.
create or replace function public.consume_public_rate_limit(
  p_scope text,
  p_key_hash text,
  p_limit integer,
  p_window_seconds integer
)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_count integer;
  v_window integer;
begin
  v_window := greatest(10, least(coalesce(p_window_seconds,60),86400));
  perform pg_advisory_xact_lock(hashtextextended(coalesce(p_scope,'')||':'||coalesce(p_key_hash,''),0));

  -- Очистка старого мусора выполняется редко, а не на каждом HTTP-запросе.
  if random() < 0.02 then
    delete from public.rate_limit_events where created_at < now() - interval '2 days';
  end if;

  select count(*) into v_count
  from public.rate_limit_events
  where scope=p_scope
    and key_hash=p_key_hash
    and created_at >= now() - make_interval(secs=>v_window);

  if v_count >= greatest(1,least(coalesce(p_limit,1),200)) then
    return false;
  end if;

  insert into public.rate_limit_events(scope,key_hash) values(p_scope,p_key_hash);
  return true;
end $$;

revoke all on function public.consume_public_rate_limit(text,text,integer,integer) from public,anon,authenticated;
grant execute on function public.consume_public_rate_limit(text,text,integer,integer) to service_role;

-- Последний рубеж против повторной публичной заявки.
create or replace function public.guard_public_booking_insert()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
declare v_recent integer;
begin
  -- Ручные записи администратора не имеют request_id и не попадают под публичный лимит.
  if new.request_id is null then return new; end if;
  if coalesce(new.phone_norm,'')='' then raise exception 'BOOKING_RATE_LIMIT'; end if;

  if exists(
    select 1 from public.bookings b
    where b.request_id is not null
      and b.phone_norm=new.phone_norm
      and lower(trim(b.pet))=lower(trim(new.pet))
      and b.service=new.service
      and lower(trim(coalesce(b.service_details->>'interest','')))=lower(trim(coalesce(new.service_details->>'interest','')))
      and b.created_at>now()-interval '30 minutes'
      and b.status not in ('rejected','cancelled')
      and b.archived_at is null
  ) then
    raise exception 'DUPLICATE_BOOKING';
  end if;

  select count(*) into v_recent
  from public.bookings b
  where b.request_id is not null
    and b.phone_norm=new.phone_norm
    and b.created_at>now()-interval '30 minutes';

  if v_recent>=3 then raise exception 'BOOKING_RATE_LIMIT'; end if;
  return new;
end $$;

drop trigger if exists trg_guard_public_booking_insert on public.bookings;
create trigger trg_guard_public_booking_insert
before insert on public.bookings
for each row execute function public.guard_public_booking_insert();

revoke execute on function public.guard_public_booking_insert() from public,anon,authenticated;
grant execute on function public.guard_public_booking_insert() to service_role;

-- Все таблицы приложения закрыты от anon/authenticated. Netlify Functions работают service_role.
alter table public.bookings enable row level security;
alter table public.clinic_services enable row level security;
alter table public.clinic_price_items enable row level security;
alter table public.push_subscriptions enable row level security;
alter table public.rate_limit_events enable row level security;
alter table public.schedule_blocks enable row level security;
alter table public.clinic_settings enable row level security;
alter table public.booking_audit enable row level security;

revoke all on public.bookings from anon,authenticated;
revoke all on public.clinic_services from anon,authenticated;
revoke all on public.clinic_price_items from anon,authenticated;
revoke all on public.push_subscriptions from anon,authenticated;
revoke all on public.rate_limit_events from anon,authenticated;
revoke all on public.schedule_blocks from anon,authenticated;
revoke all on public.clinic_settings from anon,authenticated;
revoke all on public.booking_audit from anon,authenticated;
revoke all on all sequences in schema public from anon,authenticated;

-- Явные deny-политики документируют намерение и не оставляют защиту на «RLS без policy».
drop policy if exists deny_direct_access on public.bookings;
create policy deny_direct_access on public.bookings for all to anon,authenticated using(false) with check(false);
drop policy if exists deny_direct_access on public.clinic_services;
create policy deny_direct_access on public.clinic_services for all to anon,authenticated using(false) with check(false);
drop policy if exists deny_direct_access on public.clinic_price_items;
create policy deny_direct_access on public.clinic_price_items for all to anon,authenticated using(false) with check(false);
drop policy if exists deny_direct_access on public.push_subscriptions;
create policy deny_direct_access on public.push_subscriptions for all to anon,authenticated using(false) with check(false);
drop policy if exists deny_direct_access on public.rate_limit_events;
create policy deny_direct_access on public.rate_limit_events for all to anon,authenticated using(false) with check(false);
drop policy if exists deny_direct_access on public.schedule_blocks;
create policy deny_direct_access on public.schedule_blocks for all to anon,authenticated using(false) with check(false);
drop policy if exists deny_direct_access on public.clinic_settings;
create policy deny_direct_access on public.clinic_settings for all to anon,authenticated using(false) with check(false);
drop policy if exists deny_direct_access on public.booking_audit;
create policy deny_direct_access on public.booking_audit for all to anon,authenticated using(false) with check(false);

-- Будущие таблицы/функции, созданные этим владельцем, тоже не должны случайно открываться браузерным ролям.
alter default privileges in schema public revoke all on tables from anon,authenticated;
alter default privileges in schema public revoke all on sequences from anon,authenticated;
alter default privileges in schema public revoke execute on functions from anon,authenticated;

-- На всякий случай service_role сохраняет доступ к RPC после default-ACL hardening.
grant execute on function public.consume_public_rate_limit(text,text,integer,integer) to service_role;

-- Никаких данных клиентов/записей этот скрипт не удаляет.
