-- СЕВЕРНАЯ ЗВЕЗДА — V5.1
-- Защита от спама + уведомление клиента об изменении записи + усиление безопасности.
-- Можно запускать повторно через Supabase -> SQL Editor -> New query -> Run.

create extension if not exists pgcrypto;

-- Поля для защиты от дублей и понятного уведомления клиента.
alter table public.bookings add column if not exists phone_norm text;
alter table public.bookings add column if not exists request_id text;
alter table public.bookings add column if not exists client_notice text;
alter table public.bookings add column if not exists client_notice_at timestamptz;
alter table public.bookings add column if not exists previous_booking_date date;
alter table public.bookings add column if not exists previous_booking_time time;

update public.bookings
set phone_norm = regexp_replace(coalesce(phone,''), '\D', '', 'g')
where phone_norm is null or phone_norm = '';

create index if not exists bookings_phone_norm_created_idx
on public.bookings (phone_norm, created_at desc);

create unique index if not exists bookings_request_id_unique
on public.bookings (request_id)
where request_id is not null;

-- Серверный журнал rate-limit. В нём нет исходных IP/телефонов: только HMAC-хэши.
create table if not exists public.rate_limit_events (
  id bigint generated by default as identity primary key,
  scope text not null,
  key_hash text not null,
  created_at timestamptz not null default now()
);

create index if not exists rate_limit_lookup_idx
on public.rate_limit_events (scope, key_hash, created_at desc);

create index if not exists rate_limit_created_idx
on public.rate_limit_events (created_at);

alter table public.rate_limit_events enable row level security;

create or replace function public.consume_public_rate_limit(
  p_scope text,
  p_key_hash text,
  p_limit integer,
  p_window_seconds integer
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count integer;
  v_window integer;
begin
  v_window := greatest(10, least(coalesce(p_window_seconds, 60), 86400));

  -- Один и тот же ключ проверяется последовательно, чтобы параллельные запросы
  -- не смогли одновременно проскочить лимит.
  perform pg_advisory_xact_lock(hashtextextended(coalesce(p_scope,'') || ':' || coalesce(p_key_hash,''), 0));

  delete from public.rate_limit_events
  where created_at < now() - interval '2 days';

  delete from public.rate_limit_events
  where scope = p_scope
    and key_hash = p_key_hash
    and created_at < now() - make_interval(secs => v_window);

  select count(*) into v_count
  from public.rate_limit_events
  where scope = p_scope
    and key_hash = p_key_hash
    and created_at >= now() - make_interval(secs => v_window);

  if v_count >= greatest(1, least(coalesce(p_limit, 1), 100)) then
    return false;
  end if;

  insert into public.rate_limit_events(scope, key_hash)
  values (p_scope, p_key_hash);

  return true;
end;
$$;

revoke all on function public.consume_public_rate_limit(text,text,integer,integer) from public;
revoke all on function public.consume_public_rate_limit(text,text,integer,integer) from anon;
revoke all on function public.consume_public_rate_limit(text,text,integer,integer) from authenticated;
grant execute on function public.consume_public_rate_limit(text,text,integer,integer) to service_role;

-- Все клиентские операции идут только через Netlify Functions с секретным ключом.
-- Прямой доступ к таблицам с anon/authenticated закрыт RLS.
alter table public.bookings enable row level security;
alter table public.reviews enable row level security;
alter table public.clinic_services enable row level security;
alter table public.push_subscriptions enable row level security;

-- На всякий случай подтверждаем структуру отзывов и индекс модерации.
alter table public.reviews add column if not exists is_published boolean not null default false;
create index if not exists reviews_moderation_idx
on public.reviews (is_published, created_at desc);
