-- СЕВЕРНАЯ ЗВЕЗДА — V5
-- Запускается один раз через Supabase -> SQL Editor -> New query -> Run.
-- Скрипт рассчитан на обновление поверх V4.

create extension if not exists pgcrypto;

alter table public.bookings add column if not exists admin_note text;
alter table public.bookings add column if not exists public_token text;
alter table public.bookings add column if not exists checked_in_at timestamptz;
alter table public.bookings add column if not exists started_at timestamptz;
alter table public.bookings add column if not exists completed_at timestamptz;
alter table public.bookings add column if not exists updated_at timestamptz not null default now();

update public.bookings
set public_token = encode(gen_random_bytes(24), 'hex')
where public_token is null or public_token = '';

alter table public.bookings alter column public_token set default encode(gen_random_bytes(24), 'hex');
alter table public.bookings alter column public_token set not null;

create unique index if not exists bookings_public_token_unique on public.bookings(public_token);

-- Отменённые и отклонённые записи больше не удерживают слот.
drop index if exists bookings_date_time_unique;
create unique index bookings_date_time_unique
on public.bookings (booking_date, booking_time)
where service <> 'inpatient' and status not in ('rejected','cancelled');

alter table public.bookings drop constraint if exists bookings_status_check;
alter table public.bookings add constraint bookings_status_check
check (status in ('new','accepted','arrived','in_progress','completed','rejected','no_show','cancelled'));

-- Отзывы после завершённого визита. Публикуются только после подтверждения администратора.
create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  booking_id bigint not null references public.bookings(id) on delete cascade,
  rating smallint not null check (rating between 1 and 5),
  display_name text not null,
  text text not null,
  is_published boolean not null default false,
  created_at timestamptz not null default now()
);
create unique index if not exists reviews_booking_unique on public.reviews(booking_id);

-- Услуги и цены можно менять из админки без GitHub.
create table if not exists public.clinic_services (
  service_key text primary key,
  name text not null,
  icon text not null default '🐾',
  price_label text not null default '',
  description text not null default '',
  prep text not null default '',
  sort_order integer not null default 100,
  enabled boolean not null default true,
  updated_at timestamptz not null default now(),
  constraint clinic_services_key_check check (service_key in ('exam','ultrasound','xray','vaccination','tests','inpatient','other'))
);

insert into public.clinic_services(service_key,name,icon,price_label,description,prep,sort_order,enabled) values
('exam','Осмотр','🩺','850 ₽','Первичный или повторный приём, оценка состояния питомца.','Возьмите ветеринарный паспорт и прежние результаты обследований, если они есть.',10,true),
('ultrasound','УЗИ','🫧','от 850 ₽','Ультразвуковое исследование по назначению или жалобам.','Точные требования к подготовке зависят от исследования — уточните их при записи.',20,true),
('xray','Рентген','🩻','от 1 000 ₽','Рентгенологическое исследование нужной области.','Если есть прежние снимки или заключения, возьмите их с собой.',30,true),
('vaccination','Вакцинация','💉','от 1 800 ₽','Плановая вакцинация с учётом возраста и истории прививок.','Возьмите ветеринарный паспорт. Название прошлой вакцины можно указать в заявке.',40,true),
('tests','Анализы','🧪','от 800 ₽','Лабораторные исследования по назначению врача или для контроля состояния.','Подготовка зависит от вида анализа — при необходимости клиника уточнит её заранее.',50,true),
('inpatient','Стационар','🏥','от 1 000 ₽/день','Размещение питомца на выбранный период с передачей особенностей ухода.','В заявке укажите кормление, лекарства и важные особенности поведения.',60,true),
('other','Другое','❓','уточним','Если нужной услуги нет в списке, коротко опишите запрос.','Администратор уточнит детали после получения заявки.',70,true)
on conflict (service_key) do nothing;

-- Push: один endpoint = одна подписка. Старые дубли удаляем безопасно.
create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  endpoint text not null,
  subscription jsonb not null,
  created_at timestamptz not null default now()
);

do $$
begin
  if to_regclass('public.push_subscriptions') is not null then
    execute 'delete from public.push_subscriptions a using public.push_subscriptions b where a.ctid < b.ctid and a.endpoint = b.endpoint';
    execute 'create unique index if not exists push_subscriptions_endpoint_unique on public.push_subscriptions(endpoint)';
  end if;
end $$;
