-- СЕВЕРНАЯ ЗВЕЗДА — V5
-- Запускается один раз через Supabase -> SQL Editor -> New query -> Run.
-- Скрипт рассчитан на обновление поверх V4.

create extension if not exists pgcrypto;

alter table public.bookings add column if not exists admin_note text;
alter table public.bookings add column if not exists public_token text;
alter table public.bookings add column if not exists checked_in_at timestamptz;
alter table public.bookings add column if not exists started_at timestamptz;
alter table public.bookings add column if not exists completed_at timestamptz;
alter table public.bookings add column if not exists updated_at timestamptz not null default now();

update public.bookings
set public_token = encode(gen_random_bytes(24), 'hex')
where public_token is null or public_token = '';

alter table public.bookings alter column public_token set default encode(gen_random_bytes(24), 'hex');
alter table public.bookings alter column public_token set not null;

create unique index if not exists bookings_public_token_unique on public.bookings(public_token);

-- Отменённые и отклонённые записи больше не удерживают слот.
drop index if exists bookings_date_time_unique;
create unique index bookings_date_time_unique
on public.bookings (booking_date, booking_time)
where service <> 'inpatient' and status not in ('rejected','cancelled');

alter table public.bookings drop constraint if exists bookings_status_check;
alter table public.bookings add constraint bookings_status_check
check (status in ('new','accepted','arrived','in_progress','completed','rejected','no_show','cancelled'));

-- Отзывы после завершённого визита. Публикуются только после подтверждения администратора.
create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  booking_id bigint not null references public.bookings(id) on delete cascade,
  rating smallint not null check (rating between 1 and 5),
  display_name text not null,
  text text not null,
  is_published boolean not null default false,
  created_at timestamptz not null default now()
);
create unique index if not exists reviews_booking_unique on public.reviews(booking_id);

-- Услуги и цены можно менять из админки без GitHub.
create table if not exists public.clinic_services (
  service_key text primary key,
  name text not null,
  icon text not null default '🐾',
  price_label text not null default '',
  description text not null default '',
  prep text not null default '',
  sort_order integer not null default 100,
  enabled boolean not null default true,
  updated_at timestamptz not null default now(),
  constraint clinic_services_key_check check (service_key in ('exam','ultrasound','xray','vaccination','tests','inpatient','other'))
);

insert into public.clinic_services(service_key,name,icon,price_label,description,prep,sort_order,enabled) values
('exam','Осмотр','🩺','850 ₽','Первичный или повторный приём, оценка состояния питомца.','Возьмите ветеринарный паспорт и прежние результаты обследований, если они есть.',10,true),
('ultrasound','УЗИ','🫧','от 850 ₽','Ультразвуковое исследование по назначению или жалобам.','Точные требования к подготовке зависят от исследования — уточните их при записи.',20,true),
('xray','Рентген','🩻','от 1 000 ₽','Рентгенологическое исследование нужной области.','Если есть прежние снимки или заключения, возьмите их с собой.',30,true),
('vaccination','Вакцинация','💉','от 1 800 ₽','Плановая вакцинация с учётом возраста и истории прививок.','Возьмите ветеринарный паспорт. Название прошлой вакцины можно указать в заявке.',40,true),
('tests','Анализы','🧪','от 800 ₽','Лабораторные исследования по назначению врача или для контроля состояния.','Подготовка зависит от вида анализа — при необходимости клиника уточнит её заранее.',50,true),
('inpatient','Стационар','🏥','от 1 000 ₽/день','Размещение питомца на выбранный период с передачей особенностей ухода.','В заявке укажите кормление, лекарства и важные особенности поведения.',60,true),
('other','Другое','❓','уточним','Если нужной услуги нет в списке, коротко опишите запрос.','Администратор уточнит детали после получения заявки.',70,true)
on conflict (service_key) do nothing;

-- Push: один endpoint = одна подписка. Старые дубли удаляем безопасно.
create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  endpoint text not null,
  subscription jsonb not null,
  created_at timestamptz not null default now()
);

do $$
begin
  if to_regclass('public.push_subscriptions') is not null then
    execute 'delete from public.push_subscriptions a using public.push_subscriptions b where a.ctid < b.ctid and a.endpoint = b.endpoint';
    execute 'create unique index if not exists push_subscriptions_endpoint_unique on public.push_subscriptions(endpoint)';
  end if;
end $$;


-- ============================================
-- V5.1: безопасность и комфорт
-- ============================================
-- СЕВЕРНАЯ ЗВЕЗДА — V5.1
-- Защита от спама + уведомление клиента об изменении записи + усиление безопасности.
-- Можно запускать повторно через Supabase -> SQL Editor -> New query -> Run.

create extension if not exists pgcrypto;

-- Поля для защиты от дублей и понятного уведомления клиента.
alter table public.bookings add column if not exists phone_norm text;
alter table public.bookings add column if not exists request_id text;
alter table public.bookings add column if not exists client_notice text;
alter table public.bookings add column if not exists client_notice_at timestamptz;
alter table public.bookings add column if not exists previous_booking_date date;
alter table public.bookings add column if not exists previous_booking_time time;

update public.bookings
set phone_norm = regexp_replace(coalesce(phone,''), '\D', '', 'g')
where phone_norm is null or phone_norm = '';

create index if not exists bookings_phone_norm_created_idx
on public.bookings (phone_norm, created_at desc);

create unique index if not exists bookings_request_id_unique
on public.bookings (request_id)
where request_id is not null;

-- Серверный журнал rate-limit. В нём нет исходных IP/телефонов: только HMAC-хэши.
create table if not exists public.rate_limit_events (
  id bigint generated by default as identity primary key,
  scope text not null,
  key_hash text not null,
  created_at timestamptz not null default now()
);

create index if not exists rate_limit_lookup_idx
on public.rate_limit_events (scope, key_hash, created_at desc);

create index if not exists rate_limit_created_idx
on public.rate_limit_events (created_at);

alter table public.rate_limit_events enable row level security;

create or replace function public.consume_public_rate_limit(
  p_scope text,
  p_key_hash text,
  p_limit integer,
  p_window_seconds integer
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count integer;
  v_window integer;
begin
  v_window := greatest(10, least(coalesce(p_window_seconds, 60), 86400));

  -- Один и тот же ключ проверяется последовательно, чтобы параллельные запросы
  -- не смогли одновременно проскочить лимит.
  perform pg_advisory_xact_lock(hashtextextended(coalesce(p_scope,'') || ':' || coalesce(p_key_hash,''), 0));

  delete from public.rate_limit_events
  where created_at < now() - interval '2 days';

  delete from public.rate_limit_events
  where scope = p_scope
    and key_hash = p_key_hash
    and created_at < now() - make_interval(secs => v_window);

  select count(*) into v_count
  from public.rate_limit_events
  where scope = p_scope
    and key_hash = p_key_hash
    and created_at >= now() - make_interval(secs => v_window);

  if v_count >= greatest(1, least(coalesce(p_limit, 1), 100)) then
    return false;
  end if;

  insert into public.rate_limit_events(scope, key_hash)
  values (p_scope, p_key_hash);

  return true;
end;
$$;

revoke all on function public.consume_public_rate_limit(text,text,integer,integer) from public;
revoke all on function public.consume_public_rate_limit(text,text,integer,integer) from anon;
revoke all on function public.consume_public_rate_limit(text,text,integer,integer) from authenticated;
grant execute on function public.consume_public_rate_limit(text,text,integer,integer) to service_role;

-- Все клиентские операции идут только через Netlify Functions с секретным ключом.
-- Прямой доступ к таблицам с anon/authenticated закрыт RLS.
alter table public.bookings enable row level security;
alter table public.reviews enable row level security;
alter table public.clinic_services enable row level security;
alter table public.push_subscriptions enable row level security;

-- На всякий случай подтверждаем структуру отзывов и индекс модерации.
alter table public.reviews add column if not exists is_published boolean not null default false;
create index if not exists reviews_moderation_idx
on public.reviews (is_published, created_at desc);
