const crypto=require('crypto');
const {env}=require('./_util');
function bodyTooLarge(event,maxBytes=14000){return Buffer.byteLength(event.body||'','utf8')>maxBytes}
function allowedHosts(event){const out=new Set(),h=event.headers||{};for(const raw of [h['x-forwarded-host'],h['X-Forwarded-Host'],h.host,h.Host]){const v=String(raw||'').toLowerCase().split(',')[0].trim().split(':')[0];if(v)out.add(v)}for(const raw of [process.env.URL,process.env.DEPLOY_PRIME_URL]){try{if(raw)out.add(new URL(raw).hostname.toLowerCase())}catch{}}return out}
function sameOrigin(event){const h=event.headers||{},source=h.origin||h.Origin||h.referer||h.Referer||'';if(!source)return true;try{const u=new URL(source),hosts=allowedHosts(event),local=['localhost','127.0.0.1'].includes(u.hostname);return hosts.has(u.hostname.toLowerCase())&&(u.protocol==='https:'||local)}catch{return false}}
function clientIp(event){const h=event.headers||{};return String(h['x-nf-client-connection-ip']||h['X-Nf-Client-Connection-Ip']||h['x-forwarded-for']||h['X-Forwarded-For']||'unknown').split(',')[0].trim().slice(0,120)}
function fingerprint(value){const secret=process.env.RATE_LIMIT_SECRET||process.env.ADMIN_SESSION_SECRET;if(!secret||String(secret).length<24)throw Error('Rate limit secret is missing');return crypto.createHmac('sha256',secret).update(String(value||'unknown')).digest('hex')}
async function consume(scope,rawKey,limit,windowSeconds){const {url,headers}=env();const r=await fetch(`${url}/rest/v1/rpc/consume_public_rate_limit`,{method:'POST',headers,body:JSON.stringify({p_scope:String(scope).slice(0,60),p_key_hash:fingerprint(rawKey),p_limit:Math.max(1,Math.min(200,Number(limit)||1)),p_window_seconds:Math.max(10,Math.min(86400,Number(windowSeconds)||60))})});if(!r.ok)throw Error(`Rate limit backend error ${r.status}`);return await r.json()===true}
async function guardPublicPost(event,{scope='public',ipLimit=8,ipWindow=600,key=null,keyLimit=3,keyWindow=1800,maxBytes=14000}={}){if(bodyTooLarge(event,maxBytes))return{ok:false,status:413,error:'Слишком большой запрос'};if(!sameOrigin(event))return{ok:false,status:403,error:'Запрос отклонён защитой сайта'};const ip=clientIp(event);if(!(await consume(`${scope}:ip`,ip,ipLimit,ipWindow)))return{ok:false,status:429,error:'Слишком много запросов с этого устройства. Подождите немного и попробуйте снова.'};if(key&&!(await consume(`${scope}:key`,key,keyLimit,keyWindow)))return{ok:false,status:429,error:'Слишком много запросов. Подождите немного и попробуйте снова.'};return{ok:true}}
async function guardPublicGet(event,{scope='public-read',limit=120,window=600,key=null,keyLimit=120,keyWindow=3600}={}){const ip=clientIp(event);if(!(await consume(`${scope}:ip`,ip,limit,window)))return{ok:false,status:429,error:'Слишком много запросов. Попробуйте немного позже.'};if(key&&!(await consume(`${scope}:key`,key,keyLimit,keyWindow)))return{ok:false,status:429,error:'Слишком много запросов к этой записи. Попробуйте позже.'};return{ok:true}}
module.exports={guardPublicPost,guardPublicGet,sameOrigin,bodyTooLarge,clientIp,fingerprint,consume};
