const {validate,type,dateInfo,mins}=require('./_schedule');
const {reply,env,requireAdmin,clean,normalizePhone,jsonBody}=require('./_util');
const {audit}=require('./_audit');
const SERVICES=['exam','ultrasound','xray','vaccination','tests','inpatient','other'];
const STATUSES=['new','accepted','arrived','in_progress','completed','rejected','no_show','cancelled'];
function details(s,d){d=d&&typeof d==='object'?d:{};if(s==='vaccination')return{vaccine_type:clean(d.vaccine_type,30),last_vaccine_date:d.last_vaccine_date||null};if(['ultrasound','xray'].includes(s))return{area:clean(d.area,120)};if(s==='tests')return{test_type:clean(d.test_type,30)};if(s==='inpatient')return{care:clean(d.care,500)};if(s==='other')return{reason:clean(d.reason,200)};return{}}
function time5(v){return String(v||'').slice(0,5)}
async function isBlocked(date,time,url,headers){const r=await fetch(`${url}/rest/v1/schedule_blocks?block_date=eq.${encodeURIComponent(date)}&select=start_time,end_time`,{headers});if(!r.ok)throw Error(await r.text());const m=mins(time);return(await r.json()).some(b=>{if(!b.start_time||!b.end_time)return true;const a=mins(time5(b.start_time)),z=mins(time5(b.end_time));return a!==null&&z!==null&&m>=a&&m<z})}
async function inpatientCapacity(start,end,url,headers,excludeId=null){const sr=await fetch(`${url}/rest/v1/clinic_settings?key=eq.inpatient_capacity&select=value&limit=1`,{headers});if(!sr.ok)throw Error(await sr.text());const capacity=Math.max(1,Number((await sr.json())[0]?.value?.capacity)||3);const r=await fetch(`${url}/rest/v1/bookings?service=eq.inpatient&archived_at=is.null&stay_start=lte.${encodeURIComponent(end)}&stay_end=gte.${encodeURIComponent(start)}&select=id,status`,{headers});if(!r.ok)throw Error(await r.text());const used=(await r.json()).filter(x=>String(x.id)!==String(excludeId||'')&&!['rejected','cancelled'].includes(x.status)).length;return{capacity,used}}
exports.handler=async event=>{if(event.httpMethod!=='POST')return reply(405,{error:'Method not allowed'});const a=requireAdmin(event,{csrf:true});if(!a.ok)return reply(a.status,{error:a.error});try{const b=jsonBody(event,16000),{url,headers}=env();
  if(b.action==='archive'){const id=Number(b.id);if(!id)return reply(400,{error:'Не указана запись'});const r=await fetch(`${url}/rest/v1/bookings?id=eq.${id}`,{method:'PATCH',headers:{...headers,Prefer:'return=minimal'},body:JSON.stringify({archived_at:new Date().toISOString(),updated_at:new Date().toISOString()})});if(!r.ok)throw Error(await r.text());await audit(id,'admin','archived',{});return reply(200,{ok:true})}
  if(b.action==='restore'){const id=Number(b.id);if(!id)return reply(400,{error:'Не указана запись'});const r=await fetch(`${url}/rest/v1/bookings?id=eq.${id}`,{method:'PATCH',headers:{...headers,Prefer:'return=minimal'},body:JSON.stringify({archived_at:null,updated_at:new Date().toISOString()})});if(!r.ok)throw Error(await r.text());await audit(id,'admin','restored',{});return reply(200,{ok:true})}
  if(b.action==='status'){const id=Number(b.id);if(!id||!STATUSES.includes(b.status))return reply(400,{error:'Некорректный статус'});const oldR=await fetch(`${url}/rest/v1/bookings?id=eq.${id}&select=status&limit=1`,{headers});if(!oldR.ok)throw Error(await oldR.text());const old=(await oldR.json())[0];if(!old)return reply(404,{error:'Запись не найдена'});const patch={status:b.status,updated_at:new Date().toISOString()};if(b.status==='arrived')patch.checked_in_at=new Date().toISOString();if(b.status==='in_progress')patch.started_at=new Date().toISOString();if(b.status==='completed')patch.completed_at=new Date().toISOString();const r=await fetch(`${url}/rest/v1/bookings?id=eq.${id}`,{method:'PATCH',headers:{...headers,Prefer:'return=minimal'},body:JSON.stringify(patch)});if(!r.ok)throw Error(await r.text());await audit(id,'admin','status_changed',{from:old.status,to:b.status});return reply(200,{ok:true})}
  if(b.action==='note'){const id=Number(b.id);if(!id)return reply(400,{error:'Не указана запись'});const r=await fetch(`${url}/rest/v1/bookings?id=eq.${id}`,{method:'PATCH',headers:{...headers,Prefer:'return=minimal'},body:JSON.stringify({admin_note:clean(b.admin_note,1000)||null,updated_at:new Date().toISOString()})});if(!r.ok)throw Error(await r.text());await audit(id,'admin','note_updated',{});return reply(200,{ok:true})}
  if(['create','edit'].includes(b.action)){
    const owner_name=clean(b.owner_name,100),phone=clean(b.phone,40),phone_norm=normalizePhone(phone),pet=clean(b.pet,100),pet_species=clean(b.pet_species,20)||'other',pet_age=clean(b.pet_age,40),service=clean(b.service,30)||'exam',comment=clean(b.comment,700),admin_note=clean(b.admin_note,1000),service_details=details(service,b.service_details);if(!owner_name||!phone||!pet||!SERVICES.includes(service))return reply(400,{error:'Заполните обязательные поля'});if(phone_norm.length!==11||!phone_norm.startsWith('7'))return reply(400,{error:'Проверьте номер телефона'});
    let oldRow=null,id=null;if(b.action==='edit'){id=Number(b.id);if(!id)return reply(400,{error:'Не указана запись'});const oldR=await fetch(`${url}/rest/v1/bookings?id=eq.${id}&select=*&limit=1`,{headers});if(!oldR.ok)throw Error(await oldR.text());oldRow=(await oldR.json())[0];if(!oldRow)return reply(404,{error:'Запись не найдена'})}
    let booking_date=String(b.booking_date||''),booking_time=String(b.booking_time||''),stay_start=b.stay_start?String(b.stay_start):null,stay_end=b.stay_end?String(b.stay_end):null;const inpatient=service==='inpatient';if(inpatient){if(!dateInfo(stay_start)||!dateInfo(stay_end)||stay_end<stay_start)return reply(400,{error:'Проверьте даты стационара'});booking_date=stay_start;booking_time='00:00';const cap=await inpatientCapacity(stay_start,stay_end,url,headers,id);if(cap.used>=cap.capacity)return reply(409,{error:'На этот период стационар уже заполнен'})}else{const err=validate(booking_date,booking_time,true);if(err)return reply(400,{error:err});if(await isBlocked(booking_date,booking_time,url,headers))return reply(409,{error:'Это время заблокировано в расписании'});const qr=await fetch(`${url}/rest/v1/bookings?booking_date=eq.${encodeURIComponent(booking_date)}&booking_time=eq.${encodeURIComponent(booking_time)}&archived_at=is.null&select=id,status`,{headers});if(!qr.ok)throw Error(await qr.text());if((await qr.json()).some(x=>String(x.id)!==String(id||'')&&!['rejected','cancelled'].includes(x.status)))return reply(409,{error:'Это время уже занято'})}
    const payload={owner_name,phone,phone_norm,pet,pet_species,pet_age:pet_age||null,booking_date,booking_time,comment:comment||null,admin_note:admin_note||null,booking_type:type(booking_date),service,service_details,stay_start:inpatient?stay_start:null,stay_end:inpatient?stay_end:null,updated_at:new Date().toISOString()};let changed=false,from='',to='';if(oldRow){const oldDate=oldRow.service==='inpatient'?`${oldRow.stay_start} — ${oldRow.stay_end}`:`${oldRow.booking_date} · ${time5(oldRow.booking_time)}`,newDate=inpatient?`${stay_start} — ${stay_end}`:`${booking_date} · ${booking_time}`;if(oldDate!==newDate){changed=true;from=oldDate;to=newDate;const reason=clean(b.change_reason,200),suffix=reason?` Причина: ${reason}.`:'';payload.previous_booking_date=oldRow.booking_date||null;payload.previous_booking_time=oldRow.service==='inpatient'?null:time5(oldRow.booking_time)||null;payload.client_notice=`Клиника изменила запись. Было: ${oldDate}. Стало: ${newDate}.${suffix}`;payload.client_notice_at=new Date().toISOString()}}
    let r;if(b.action==='create'){payload.status='accepted';r=await fetch(`${url}/rest/v1/bookings`,{method:'POST',headers:{...headers,Prefer:'return=representation'},body:JSON.stringify(payload)})}else r=await fetch(`${url}/rest/v1/bookings?id=eq.${id}`,{method:'PATCH',headers:{...headers,Prefer:'return=representation'},body:JSON.stringify(payload)});if(!r.ok){const t=await r.text();if(r.status===409||t.includes('23505'))return reply(409,{error:'Это время уже занято'});throw Error(t)}const row=(await r.json())[0];await audit(row.id,'admin',b.action==='create'?'created_by_admin':'edited',{schedule_changed:changed,from,to,service});return reply(200,{ok:true,id:row.id,schedule_changed:changed})
  }
  return reply(400,{error:'Неизвестное действие'})
}catch(e){console.error(e);return reply(e.status||500,{error:e.status?e.message:'Не удалось изменить запись'})}};
