const {validate,type,now,today,mins}=require('./_schedule');
const {reply,env,clean,jsonBody}=require('./_util');
const {sendPush}=require('./_push');
const {guardPublicPost,guardPublicGet}=require('./_public-guard');
const {audit}=require('./_audit');
function safe(row){return{id:row.id,pet:row.pet,pet_age:row.pet_age,booking_date:row.booking_date,booking_time:String(row.booking_time||'').slice(0,5),booking_type:row.booking_type,status:row.status,service:row.service,stay_start:row.stay_start,stay_end:row.stay_end,created_at:row.created_at,updated_at:row.updated_at,client_notice:row.client_notice||null,client_notice_at:row.client_notice_at||null,previous_booking_date:row.previous_booking_date||null,previous_booking_time:row.previous_booking_time?String(row.previous_booking_time).slice(0,5):null}}
async function blocked(date,time,url,headers){const r=await fetch(`${url}/rest/v1/schedule_blocks?block_date=eq.${encodeURIComponent(date)}&select=start_time,end_time`,{headers});if(!r.ok)throw Error(await r.text());const m=mins(time);return(await r.json()).some(b=>{if(!b.start_time||!b.end_time)return true;const a=mins(String(b.start_time).slice(0,5)),z=mins(String(b.end_time).slice(0,5));return a!==null&&z!==null&&m>=a&&m<z})}
exports.handler=async event=>{try{const {url,headers}=env(),qs=event.queryStringParameters||{},token=clean(qs.token||'',100);if(event.httpMethod==='GET'){if(!token)return reply(400,{error:'Ссылка на заявку неполная'});const g=await guardPublicGet(event,{scope:'booking-read',limit:180,window:3600,key:token,keyLimit:120,keyWindow:3600});if(!g.ok)return reply(g.status,{error:g.error});const r=await fetch(`${url}/rest/v1/bookings?public_token=eq.${encodeURIComponent(token)}&archived_at=is.null&select=*&limit=1`,{headers});if(!r.ok)throw Error(await r.text());const row=(await r.json())[0];if(!row)return reply(404,{error:'Запись не найдена или больше недоступна'});return reply(200,{booking:safe(row)})}
  if(event.httpMethod==='POST'){const b=jsonBody(event,5000),tok=clean(b.token,100);if(!tok)return reply(400,{error:'Ссылка на заявку неполная'});const guard=await guardPublicPost(event,{scope:'booking-action',ipLimit:30,ipWindow:900,key:tok,keyLimit:10,keyWindow:900,maxBytes:5000});if(!guard.ok)return reply(guard.status,{error:guard.error});const fr=await fetch(`${url}/rest/v1/bookings?public_token=eq.${encodeURIComponent(tok)}&archived_at=is.null&select=*&limit=1`,{headers});if(!fr.ok)throw Error(await fr.text());const row=(await fr.json())[0];if(!row)return reply(404,{error:'Запись не найдена'});if(['completed','no_show','rejected','cancelled'].includes(row.status))return reply(400,{error:'Эту запись уже нельзя изменить'});
    if(b.action==='cancel'){const pr=await fetch(`${url}/rest/v1/bookings?id=eq.${row.id}`,{method:'PATCH',headers:{...headers,Prefer:'return=minimal'},body:JSON.stringify({status:'cancelled',client_notice:null,client_notice_at:null,previous_booking_date:null,previous_booking_time:null,updated_at:new Date().toISOString()})});if(!pr.ok)throw Error(await pr.text());await audit(row.id,'client','cancelled',{date:row.booking_date,time:String(row.booking_time).slice(0,5)});await sendPush({title:'↩️ Клиент отменил запись',body:`${row.pet}, ${row.booking_date} ${String(row.booking_time).slice(0,5)}`,url:'/admin.html#notifications'});return reply(200,{ok:true,status:'cancelled'})}
    if(b.action==='reschedule'){if(row.service==='inpatient')return reply(400,{error:'Для стационара изменение дат согласуйте с клиникой'});const date=String(b.booking_date||''),time=String(b.booking_time||''),err=validate(date,time);if(err)return reply(400,{error:err});if(date===today()){const n=now();if(mins(time)<=n.getHours()*60+n.getMinutes())return reply(400,{error:'Это время уже прошло'})}if(await blocked(date,time,url,headers))return reply(409,{error:'Это время недоступно'});const qr=await fetch(`${url}/rest/v1/bookings?booking_date=eq.${encodeURIComponent(date)}&booking_time=eq.${encodeURIComponent(time)}&archived_at=is.null&select=id,status`,{headers});if(!qr.ok)throw Error(await qr.text());if((await qr.json()).some(x=>String(x.id)!==String(row.id)&&!['rejected','cancelled'].includes(x.status)))return reply(409,{error:'Это время уже занято'});const oldDate=row.booking_date,oldTime=String(row.booking_time).slice(0,5),pr=await fetch(`${url}/rest/v1/bookings?id=eq.${row.id}`,{method:'PATCH',headers:{...headers,Prefer:'return=minimal'},body:JSON.stringify({booking_date:date,booking_time:time,booking_type:type(date),status:'new',client_notice:null,client_notice_at:null,previous_booking_date:null,previous_booking_time:null,updated_at:new Date().toISOString()})});if(!pr.ok)throw Error(await pr.text());await audit(row.id,'client','rescheduled',{from:`${oldDate} ${oldTime}`,to:`${date} ${time}`});await sendPush({title:'🗓 Клиент перенёс запись',body:`${row.pet}: ${oldDate} ${oldTime} → ${date} ${time}`,url:'/admin.html#notifications'});return reply(200,{ok:true,status:'new'})}return reply(400,{error:'Неизвестное действие'})}
  return reply(405,{error:'Method not allowed'})
}catch(e){console.error(e);return reply(e.status||500,{error:e.status?e.message:'Не удалось обработать запись'})}};
