const fs=require('fs');const path=require('path');const vm=require('vm');const cp=require('child_process');
const root=path.resolve(__dirname,'..');const fail=m=>{console.error('\n[VALIDATE] ERROR: '+m+'\n');process.exit(1)},ok=m=>console.log('[VALIDATE] OK: '+m),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const required=['index.html','admin.html','booking.html','prices.html','privacy.html','404.html','netlify.toml','package.json','site.webmanifest','admin-manifest.webmanifest','robots.txt','sitemap.xml','sw.js','icons/site-icon-192.png','icons/site-icon-512.png','icons/admin-icon-192.png','icons/admin-icon-512.png','netlify/functions/send-booking.js','netlify/functions/public-booking.js','netlify/functions/manage-booking.js','netlify/functions/get-bookings.js','netlify/functions/admin-session.js','netlify/functions/health.js','netlify/functions/schedule.js','netlify/functions/audit.js','netlify/functions/export-bookings.js','netlify/functions/price-items.js','netlify/functions/clinic-settings.js','supabase/SECURITY-HARDENING-MIGRATION.sql','SECURITY-REPORT.md'];
for(const f of required)if(!fs.existsSync(path.join(root,f)))fail('Нет обязательного файла: '+f);ok('обязательные файлы на месте');
for(const f of ['index.html','admin.html','booking.html','prices.html','privacy.html','404.html']){const s=read(f).trimStart().toLowerCase();if(!s.startsWith('<!doctype html')&&!s.startsWith('<html'))fail(f+' не похож на HTML')}ok('HTML-файлы не перепутаны');
for(const f of ['package.json','site.webmanifest','admin-manifest.webmanifest'])try{JSON.parse(read(f))}catch(e){fail(f+' содержит невалидный JSON: '+e.message)}ok('JSON и webmanifest валидны');
const toml=read('netlify.toml');if(!/^\[build\]/m.test(toml)||!/functions\s*=\s*"netlify\/functions"/.test(toml))fail('netlify.toml не похож на конфиг Netlify');if(/^\s*(?:create|alter|--\s*СЕВЕРНАЯ)/im.test(toml))fail('В netlify.toml обнаружен SQL');ok('netlify.toml выглядит корректно');
const sig=Buffer.from([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a]);for(const f of required.filter(x=>x.endsWith('.png'))){const b=fs.readFileSync(path.join(root,f));if(b.length<64||!b.subarray(0,8).equals(sig))fail(f+' не PNG')}ok('иконки являются PNG');
const js=[];function walk(d){for(const n of fs.readdirSync(d,{withFileTypes:true})){const p=path.join(d,n.name);if(n.isDirectory())walk(p);else if(n.isFile()&&p.endsWith('.js'))js.push(p)}}walk(path.join(root,'netlify','functions'));js.push(path.join(root,'sw.js'));for(const p of js){const r=cp.spawnSync(process.execPath,['--check',p],{encoding:'utf8'});if(r.status!==0)fail(path.relative(root,p)+' не проходит node --check:\n'+(r.stderr||r.stdout))}ok('серверный JavaScript проходит node --check');
for(const f of ['index.html','admin.html','booking.html','prices.html']){const html=read(f),blocks=[...html.matchAll(/<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/gi)].map(x=>x[1]);blocks.forEach((code,i)=>{try{new vm.Script(code,{filename:f+'#inline-'+(i+1)})}catch(e){fail(f+' содержит синтаксическую ошибку JS: '+e.message)}})}ok('встроенный JavaScript страниц синтаксически корректен');
const index=read('index.html');if(/Отзывы|Защита от случайных дублей и спама/i.test(index))fail('На клиентской странице остался удалённый/технический блок');if(/\.reveal\s*\{[^}]*opacity\s*:\s*0/i.test(index))fail('Основной контент может быть скрыт CSS без JavaScript');if(!/privacy\.html/.test(index))fail('Нет ссылки на политику обработки данных');if(!/consent/i.test(index))fail('Нет согласия у формы');if(!/prices\.html/.test(index))fail('Нет ссылки на полный прайс');ok('клиентская страница прошла UX-safety checks');if(!/id="themeBtn"/.test(index)||/id="themeBtn"[^>]*desktopOnly/.test(index))fail('Переключатель темы на главной скрыт или отсутствует');if(/Забота о питомце\s*<span>без лишней суеты<\/span>/i.test(index))fail('На главной остался старый слоган');if(!/id="themeBtn"/.test(read('prices.html')))fail('На странице прайса отсутствует переключатель темы');if(!/tiny\.book\{background:#edf7f2;color:#14231d\}/.test(index))fail('Тёмная тема может скрывать подпись кнопки записи');if(/id="testsBox"|id="testType"|>Общие<\/option>/.test(index))fail('В форме осталась старая искусственная классификация анализов');if(/Конкретная услуга\s*\/\s*процедура|id="specificServices"/.test(index))fail('В форме снова появился дублирующий выбор конкретной услуги');if(!/id="servicePickerPanel"/.test(index)||!/id="requestedItemKey"/.test(index)||!/setSelectedService/.test(index))fail('Единый выбор услуги из прайса не подключён');if(/id="fullPriceTab"|id="homePriceCatalog"/.test(index))fail('Полный прайс снова дублируется прямо на главной');if(!/priceShortcut/.test(index)||!/prices\.html/.test(index))fail('Нет компактного перехода к полному прайсу');if(!/categoryGrid/.test(read('prices.html'))||!/Разделы прайса/.test(read('prices.html')))fail('Полный прайс снова показывает длинную простыню вместо навигации по разделам');
for(const f of ['index.html','admin.html','booking.html','prices.html']){const h=read(f);if(/стационар/i.test(h))fail(f+' содержит информацию о стационаре')}ok('информация о стационаре удалена из интерфейса');
const admin=read('admin.html');for(const ep of ['admin-session','schedule','audit','export-bookings','push-test','price-items'])if(!admin.includes('/.netlify/functions/'+ep))fail('Админка ожидает отсутствующий endpoint '+ep);if(!/openNewBookings/.test(admin)||!/newCount/.test(admin))fail('Счётчик новых заявок не связан со списком новых заявок');ok('админские endpoints и кликабельные новые заявки согласованы');if(!/mobileDock/.test(admin)||!/nextPatientCard/.test(admin)||!/siteSettingsForm/.test(admin)||!/checkSystem/.test(admin))fail('Не найден новый слой удобства админки');if(!/clinic-settings/.test(admin)||!/clinic-settings/.test(index))fail('Настройки сайта не связаны с клиентом и админкой');ok('центр управления сайтом и мобильные быстрые действия подключены');if(!/mobileDock\.ready/.test(admin)||!/showLogin\(\).*mobileDock/.test(admin))fail('Мобильная панель может появиться до входа');
const booking=read('booking.html');if(/stay_start|stay_end|stayStart|stayEnd/i.test(booking))fail('В клиентской записи осталась старая логика стационара');
const migration=read('supabase/SECURITY-HARDENING-MIGRATION.sql');if(!/TRAUMA|30-минут/i.test(migration)&&!read('netlify/functions/_schedule.js').includes('TRAUMA_SLOT=30'))fail('Не найден 30-минутный интервал травматолога');if(/^\('[^']+','Стационар'/mi.test(migration))fail('В новый прайс попал удалённый раздел');const seeded=(migration.match(/^\('[a-z]+-\d{3}'/gm)||[]).length;if(seeded<130)fail('В полном прайсе слишком мало позиций: '+seeded);ok('полный прайс содержит '+seeded+' позиций и отдельную логику травматолога');
const rootJs=fs.readdirSync(root).filter(x=>x.endsWith('.js')&&x!=='sw.js');if(rootJs.length)fail('JS-файлы не должны лежать в корне: '+rootJs.join(', '));if(fs.readdirSync(root).some(x=>/^__.*test/i.test(x)))fail('В production остался тестовый HTML/файл');if(fs.existsSync(path.join(root,'reviews.js'))||fs.existsSync(path.join(root,'netlify/functions/reviews.js')))fail('Отзывы не удалены из production');if(fs.existsSync(path.join(root,'netlify/functions/settings.js')))fail('Устаревший endpoint settings не удалён');ok('production-структура чистая');
// Security invariants: keep the highest-risk regressions from returning in later releases.
if(/public_token\s*:\s*b\.public_token/.test(admin))fail('Bearer public_token попал в офлайн-кэш админки');
if(/onclick=[\"'][^\"']*quickFromPet\s*\(\s*[\"']\$\{/i.test(admin))fail('Потенциальный stored XSS: пользовательские данные внутри inline onclick');
if(!/booking\.html#t=/.test(index)||!/booking\.html#t=/.test(admin)||!/booking\.html#t=/.test(booking))fail('Новые приватные ссылки должны использовать fragment #t=');
if(!/action:'read',token/.test(index)||!/action:'read',token/.test(booking))fail('Приватное чтение записи должно отправлять bearer token в JSON body');
for(const f of ['index.html','admin.html','booking.html','prices.html','privacy.html','404.html','sw.js']){const x=read(f);if(/process\.env/.test(x))fail(f+' содержит server-side env обращение');for(const n of ['SUPABASE_SECRET_KEY','VAPID_PRIVATE_KEY','ADMIN_PASSWORD','ADMIN_SESSION_SECRET','RATE_LIMIT_SECRET'])if(x.includes(n))fail(f+' содержит имя серверного секрета '+n)}
const securitySql=read('supabase/SECURITY-HARDENING-MIGRATION.sql');
for(const x of ['revoke all on public.bookings from anon,authenticated','create policy deny_direct_access on public.bookings','create unique index bookings_date_time_unique','DUPLICATE_BOOKING'])if(!securitySql.toLowerCase().includes(x.toLowerCase()))fail('Security migration не содержит обязательную защиту: '+x);
const sw=read('sw.js');if(!sw.includes("u.pathname.startsWith('/.netlify/functions/')"))fail('Service worker может кэшировать API');if(!sw.includes("url.startsWith('/admin.html')"))fail('Push notificationclick не ограничен админкой');
ok('security invariants проверены');
console.log('\n[VALIDATE] PROJECT READY FOR NETLIFY\n');
